version: "3.8"

services:
  frontend:
    image: ghcr.io/caitoor/starbugs_frontend:latest
    environment:
      - VITE_API_BASE_URL=https://${BACKEND_SUBDOMAIN}.${DOMAIN}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.rule=Host(`${FRONTEND_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.entrypoints=https"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.tls=true"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.tls.certresolver=cf"
        - "traefik.http.services.${FRONTEND_SUBDOMAIN}.loadbalancer.server.port=80"
        - "traefik.http.services.${FRONTEND_SUBDOMAIN}.loadbalancer.server.scheme=http"
    networks:
      - proxy

  backend:
    image: ghcr.io/caitoor/starbugs_api:latest
    environment:
      - API_PORT=${API_PORT}
      - FRONTEND_URL=https://${FRONTEND_SUBDOMAIN}.${DOMAIN}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URI=mongodb://${MONGO_CONTAINER_NAME}:27017/${MONGO_DB}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.rule=Host(`${BACKEND_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.entrypoints=https"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.tls=true"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.tls.certresolver=cf"
        - "traefik.http.services.${BACKEND_SUBDOMAIN}.loadbalancer.server.port=${API_PORT}"
        - "traefik.http.services.${BACKEND_SUBDOMAIN}.loadbalancer.server.scheme=https"
    ports:
      - "3000:3000"
    networks:
      - proxy
      - starbugs_network

  mongo:
    image: mongo:7
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faebs
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
    networks:
      - proxy
      - starbugs_network

networks:
  proxy:
    external: true
  starbugs_network:
    
volumes:
  mongo_data: