version: "3.6"

services:
  frontend:
    image: ghcr.io/caitoor/starbugs_frontend:latest
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.frontend.rule=Host(`starbugs.sweavs.de`)"
        - "traefik.http.routers.frontend.entrypoints=https"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=cf"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
        - "traefik.http.services.frontend.loadbalancer.server.scheme=http"
    networks:
      - proxy

  backend:
    image: ghcr.io/caitoor/starbugs_api:latest
    environment:
      - API_PORT=3000
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=starinformation
      - MONGO_COLLECTION=athyg
      - FRONTEND_URL=http://starbugs.sweavs.de
      - MONGO_INITDB_ROOT_USERNAME=faebs
      - MONGO_INITDB_ROOT_PASSWORD=secret
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.backend.rule=Host(`api.starbugs.sweavs.de`)"
        - "traefik.http.routers.backend.entrypoints=https"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=cf"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"
        - "traefik.http.services.backend.loadbalancer.server.scheme=http"
    networks:
      - proxy
      - starbugs

  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faebs
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
    networks:
      - proxy
      - starbugs

networks:
  proxy:
    external: true
  starbugs:
    

volumes:
  mongo_data:
